
name: Deploy to GitHub Pages

# Run workflowe on every push to the master branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses Github's checkout action to checkout code from the master branch
    - uses: Actions/checkout@v2

    # sets up .Net Core SDK 6.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # publishes Blazor project to the release-folder
    - name: Publish .Net Core Project
      run: dotnet publish -c Release -o release --nologo

    # changes the base-tag in index.html from "/" to 'Proj5' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to Proj5
      run: sed -i 's/<base href-"\/" \/>/<base href="\/Proj5\/" \/>/g' release/wwwroot/index.html

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GithUb pagaes to not treat this as a Jekyll project
    - name: Add .noJekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
